// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1DS95XSVlHamJrFW6UNFSOKjK7WjVQXI',
    appId: '1:906103670460:web:860e4320ee13f96d00f2b9',
    messagingSenderId: '906103670460',
    projectId: 'ai-buddy-dev-ayush',
    authDomain: 'ai-buddy-dev-ayush.firebaseapp.com',
    storageBucket: 'ai-buddy-dev-ayush.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfI1RNrczTCYiFckiES8iYl2IHdvsaflk',
    appId: '1:906103670460:android:243e1f458db8cf6800f2b9',
    messagingSenderId: '906103670460',
    projectId: 'ai-buddy-dev-ayush',
    storageBucket: 'ai-buddy-dev-ayush.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB08U5v0HzVXjxZA6C3loZ339gIavi1kSk',
    appId: '1:906103670460:ios:8c1783db172913bf00f2b9',
    messagingSenderId: '906103670460',
    projectId: 'ai-buddy-dev-ayush',
    storageBucket: 'ai-buddy-dev-ayush.firebasestorage.app',
    iosBundleId: 'com.example.aiBuddy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB08U5v0HzVXjxZA6C3loZ339gIavi1kSk',
    appId: '1:906103670460:ios:8c1783db172913bf00f2b9',
    messagingSenderId: '906103670460',
    projectId: 'ai-buddy-dev-ayush',
    storageBucket: 'ai-buddy-dev-ayush.firebasestorage.app',
    iosBundleId: 'com.example.aiBuddy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1DS95XSVlHamJrFW6UNFSOKjK7WjVQXI',
    appId: '1:906103670460:web:7f5f6bdfc4bdb37400f2b9',
    messagingSenderId: '906103670460',
    projectId: 'ai-buddy-dev-ayush',
    authDomain: 'ai-buddy-dev-ayush.firebaseapp.com',
    storageBucket: 'ai-buddy-dev-ayush.firebasestorage.app',
  );
}
